export enum QueryKeyEnum {
  USER = 'USER',
  CHILD = 'CHILD',
  CHILDREN = 'CHILDREN',
  DASHBOARD_SUMMARY = 'DASHBOARD_SUMMARY',
  DASHBOARD_ALERTS_BY_TYPE = 'DASHBOARD_ALERTS_BY_TYPE',
  DASHBOARD_ALERTS_BY_SEVERITY = 'DASHBOARD_ALERTS_BY_SEVERITY',
  DASHBOARD_ALERTS_BY_NEIGHBORHOOD = 'DASHBOARD_ALERTS_BY_NEIGHBORHOOD',
  CHILDREN_NEIGHBORHOODS = 'CHILDREN_NEIGHBORHOODS'
}
